name: Second Hello World
on:
  workflow_dispatch

jobs:
  first-step:
    runs-on: ubuntu:24.04
    steps:
      - run: echo Hello World

  second-step-python:
    runs-on: ubuntu:24.04
    steps:
      - run: print("Hello World")
        shell: python
  
  third-step-java:
    runs-on: ubuntu:24.04
    steps:
      - uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "World and Aleandro"
